### ISSUE TITLE
Road to Embera 2.0

### ISSUE THREAD

**Issue by mpratt** [mpratt/Embera#15]
I am starting to think about version 2.0 of this library. There are some areas of improvement and perhaps I might need to introduce some changes to the API that might break compatibility.

As of now, the main points that I think are very important in order to release a 2.0 version are:

- [ ] Reduce Class complexity.
- [ ] Change the way the library handles custom Oembed Providers. In other words, make it simpler!
- [ ] Expose an API that allows the user to modify the Oembed response directly.
- [ ] Use Interfaces so that developers can change parts of the Library via dependency injection.
- [ ] I am not happy with the configuration array, lets simplify it a bit
- [ ] Lets get away from the Formatter Class and find another way to use "templates"

Other stuff I've been thinking about that I'm not sure that should be implemented on Embera are:

- [ ] A simple caching system (probably file based) for urls
- [ ] A global (or per Provider) way to handle `https` embeds
- [ ] Normalize the oembed responses (some providers reply with thumbnailWidth others with thumbnal_width :unamused: )
- [ ] Add Embedly/NoEmbed/Iframely providers
- [ ] Look into responsive embeds and the possibility to implement them on some providers

We all know that PHP 5.3 is deprecated now (since August 2014), but I still plan on supporting it. Yeah, I know how it feels when you're stuck on a shitty environment without ways to upgrade.. I feel your pain too..

I'm going to keep fixing bugs and adding providers to version 1.x.x. Version 2.0 should be available somewhere in february 2015. 

I will make a `2.0` branch available over the weekend in order to start playing.

Feel free to comment and share your ideas/thoughts for this library.

* Edit: grammar :(

**Comment by iparamonau** [comment]
Hi Michael, Ivan from [Iframely](https://iframely.com) here.  

I see you put us on your roadmap, so just wanted to reach out and let you know that we have open oEmbed proxy endpoint that you can put into your package, without API key etc: 

`http://open.iframe.ly/api/oembed?url=...&origin=embera`

Read more [here](http://oembedapi.com). Generally, it might be a good idea just to have a fallback to "oEmbed proxy" with configurable API endpoint. This would cover us, Noembed, Embedly, our [self-hosted](https://github.com/itteco/iframely) version, etc. Especially if the config string would allow additional query-string parameters in it.

**Comment by mpratt** [comment]
I'm going to close this issue for now and write a new road map.

I'm restarting work on the new version of this library, focusing on other stuff and this road map is not acurrate anymore (It's really old and I couldnt work on it). 

I'm planning on making everything available in a new branch, once I have the main structure/design ready. When that's done, Im writing a new road map.

Sorry :(

**Comment by interfixnet** [comment]
Any progress on a new roadmap? I'm getting occasional load times of 15-20 seconds to generate embeds for just 3 video URLs on the page. Right now I'm forcing it to fake/offline mode for youtube but that doesn't work for vimeo even though the provider list says it should,  so a cache system would be very helpful.
