### ISSUE TITLE
Embeds in <pre> tags

### ISSUE THREAD

**Issue by sunnysingh** [mpratt/Embera#22]
Embera does not take into consideration when URLs are posted within `<pre><code>` tags. Since these tags (code blocks) are normally used for demonstrating code, I don't want a URL that happens to be a provider to be parsed within these code blocks.

I believe this should be a config option in Embera, or at the very least how would I be able to do this myself?

**Comment by mpratt** [comment]
Hi **sunnysingh**,

Thats a good idea but I dont have time to implement it right. Perhaps for the next big version I'll be able to add an `html aware` option.

As a workaround you could just extract the data inside the `<pre></pre>` tags, pass the text through Embera and put the data inside the `<pre>` tags again.

Try with something like this:

```php
$text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. consectetur, ac dignissim https://www.youtube.com/watch?v=yzTuBuRdAyA .
<pre>
   Etiam scelerisque rutrum justo, https://www.youtube.com/watch?v=yzTuBuRdAyA 
</pre>';

$holder = array();
if (strpos($text, '<pre') !== false) {
    // Reserve the content inside the <pre> tags
    $text = preg_replace_callback('/\\s*(<pre\\b[^>]*?>[\\s\\S]*?<\\/pre>)\\s*/i', function ($content) use (&$holder) {
        $placeholder = '%' . md5(time() . count($holder) . mt_rand(0, 500)) . '%';
        $holder[$placeholder] = $content['1'];
        return $placeholder;
    }, $text);
}

$embera = new \Embera\Embera();
$text = $embera->autoEmbed($text);

if (!empty($holder)) {
    $text = str_replace(array_keys($holder), array_values($holder), $text);
}

echo $text;
```

I think that should work, however you can organize the code better. I would create a new class called something like `ReserveTag` and put the logic into it.

By doing this you end up with something like this:

```php
$text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. consectetur, ac dignissim https://www.youtube.com/watch?v=yzTuBuRdAyA .
<pre>
   Etiam scelerisque rutrum justo, https://www.youtube.com/watch?v=yzTuBuRdAyA 
</pre>';

$reserve = new ReserveTag('pre');
$embera = new \Embera\Embera();
$text = $embera->autoEmbed($reserve->filter($text));
echo $reserve->restore($text);
```

Tell me if it helps!

**Comment by sunnysingh** [comment]
This is the best reply that I've seen, I really appreciate in you providing me a code sample and I can't believe that I didn't think of doing it this way.

Your code definitely works for this purpose, I'll use it in the meantime. The one change that I made was replace `pre` with `code` so that inline code would not be parsed either.

**Comment by mpratt** [comment]
Im glad it works! 

Im marking this issue as closed but believe me, I'll keep this in the back of my head for the next major release of this library!

Cheers!
