### ISSUE TITLE
Bug: custom_params doesn't work for non-default providers

### ISSUE THREAD

**Issue by assembledadam** [mpratt/Embera#29]
```
$config = array(
    'custom_params' => array(
        'CustomProvider' => array('align' => 'center', 'hide_media' => 1)
    )
);

$embera = new \Embera\Embera($config);

$embera->addProvider('custom.com', 'ExampleLib\CustomProvider);

$response = $embera->getUrlInfo('http://custom.com/foo/bar'); // does not pass custom_params
```

Doesn't work, because Providers::addProvider() is fired after Providers::extractCustomParams().

**Comment by assembledadam** [comment]
Oh, I should mention that a workaround is to pass parameters to the addProvider() method on initialisation.

**Comment by mpratt** [comment]
Hi **assembledadam**!

You are indeed right! 

If you ask me, I think it makes more sense to set custom parameters for custom providers right there on the `addProvider()` method. However I fixed the bug and now you can also set them on the main config array in construction.

Thanks for the report!
