### ISSUE TITLE
twiitter embed doesn't work

### ISSUE THREAD

**Issue by chuja3** [mpratt/Embera#35]
https://twitter.com/RalphGarman/status/362589356495605762/
Array ( [0] => 0: Invalid response for https://publish.twitter.com/oembed.json?url=https%3A%2F%2Ftwitter.com%2FRalphGarman%2Fstatus%2F362589356495605762 [1] => 0: Invalid response for https://publish.twitter.com/oembed.json?url=https%3A%2F%2Ftwitter.com%2FRalphGarman%2Fstatus%2F362589356495605762 )

**Comment by mpratt** [comment]
Hi Chuja3,
I cannot replicate, It is working fine for me.

```php
<?php
require 'Autoload.php';
$e = new Embera\Embera();
$url = 'https://twitter.com/RalphGarman/status/362589356495605762/';
echo $e->autoEmbed($url);
print_r($e->getUrlInfo($url));
```

Returns:

```
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Love my Babble Brother, <a href="https://twitter.com/ThatKevinSmith">@ThatKevinSmith</a>? Me too! Celebrate his birthday this Friday at 10pm w/ HOLLYWOOD BABBLE-ON!  <a href="http://t.co/dKXzZUyoq9">http://t.co/dKXzZUyoq9</a></p>&mdash; Ralph Garman (@RalphGarman) <a href="https://twitter.com/RalphGarman/status/362589356495605762">July 31, 2013</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Array
(
    [https://twitter.com/RalphGarman/status/362589356495605762/] => Array
        (
            [embera_using_fake] => 0
            [url] => https://twitter.com/RalphGarman/status/362589356495605762
            [author_name] => Ralph Garman
            [author_url] => https://twitter.com/RalphGarman
            [html] => <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Love my Babble Brother, <a href="https://twitter.com/ThatKevinSmith">@ThatKevinSmith</a>? Me too! Celebrate his birthday this Friday at 10pm w/ HOLLYWOOD BABBLE-ON!  <a href="http://t.co/dKXzZUyoq9">http://t.co/dKXzZUyoq9</a></p>&mdash; Ralph Garman (@RalphGarman) <a href="https://twitter.com/RalphGarman/status/362589356495605762">July 31, 2013</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
            [width] => 550
            [type] => rich
            [cache_age] => 3153600000
            [provider_name] => Twitter
            [provider_url] => https://twitter.com
            [height] => 
            [version] => 1.0
        )

)
```

Can you please try that code and tell me what it returns?

**Comment by chuja3** [comment]
Nice, thank you for your support, it work fine now in online server, I was testing it first time in localhost, that's way it doesn't work for me, you can see online demo in this link, http://www.emagzen.com/topic/test/6/318/i.html?p=355
but i have some problém in facebook embed, !! the links doesn't work fine, any idea ?!

**Comment by mpratt** [comment]
Hi, Chuja, can you please try this?

Add the following method to Embera/Providers/Facebook.php and tell me if it works

```php
    protected function modifyResponse(array $response = array())
    {
        if (!empty($response['html'])) {
            // Backup the real response
            $response['raw']['html'] = $response['html'];
            $iframe = '<iframe src="https://www.facebook.com/plugins/post.php?href={url}&width={width}&show_text=true&appId" width="{width}" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>';
            $table = array(
                '{url}' => rawurlencode($this->url),
                '{width}' => $response['width'],
            );

            $response['html'] = str_replace(array_keys($table), array_values($table), $iframe);
        }

        return $response;
    }
```

**Comment by chuja3** [comment]
now its ok, thank you, but still a little problem, about the height !! :+1:

**Comment by mpratt** [comment]
Can you try with this one?

```php
    protected function modifyResponse(array $response = array())
    {
        if (!empty($response['html'])) {
            $iframe = '<iframe src="https://www.facebook.com/plugins/post.php?href={url}&width={width}&height={height}&show_text=true&appId" width="{width}" height="{height}"" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>';

            if (!empty($response['height'])) {
                $height = $response['height'];
            } else {
                $height = min(650, (int) ($response['width'] + 100));
            }

            $table = array(
                '{url}' => rawurlencode($this->url),
                '{width}' => $response['width'],
                '{height}' => $height,
            );

            // Backup the real response
            $response['raw']['html'] = $response['html'];

            // Replace the html response
            $response['html'] = str_replace(array_keys($table), array_values($table), $iframe);
        }

        return $response;
    }
```

The problem with the real html response, seems to be that the facebook oembed endpoint always returns a javascript code  with the famous `<div id="fb-root"></div>`. Since you have more than one facebook embed, it causes issues when a div with the same id is defined more than once in a html page.

It could also cause issues when using the facebook js sdk, which also requires `<div id="fb-root"></div>` on top of the page. 

So the safe choice is to modify the html response and use an iframe, the problem is calculating the right height for the embed. I think this should be enough, however, let me know, so that I can make the change upstream and tag a new version :)

**Comment by chuja3** [comment]
I try hard width css and jquey to fix this and make the height dynamic, but I think that I will accept it like this, thanks anyway ! :+1:

**Comment by mpratt** [comment]
Did you try using the last `modifyResponse()` method I wrote?
Just delete the first one and add the new one I wrote in my last post.

**Comment by chuja3** [comment]
yes and it gives me a fixed height value : 650px

**Comment by mpratt** [comment]
Im going to push this modification to the main library. Its just easier to handle. Im giving the iframe also a distinct id and class, so it should be easier to overwrite the height/width via css.

Thanks for the report!
