### ISSUE TITLE
Facebook offline support?

### ISSUE THREAD

**Issue by andrewpros** [mpratt/Embera#46]
Hi.
Why fb doesn't have offline support?

@mpratt

**Comment by mpratt** [comment]
Hi,
Offline support, only means that we are able to create a response based on the given url. In the case of facebook we are not able to create a response url, based on the original url.

Im so sorry.

**Comment by andrewpros** [comment]
Yes you can.

**Comment by mpratt** [comment]
Oh! I didnt know that. 
Can you please tell me how? Or give me an example?

**Comment by mpratt** [comment]
Well, it turns out you are completely right @andrewpros 
For most of the cases we can create a fake response.

I'll be looking into it next weekend.

**Comment by andrewpros** [comment]
@mpratt Thx, but i don't have any PR.

**Comment by PayteR** [comment]
Any news about this issue?

**Comment by PayteR** [comment]
PR added https://github.com/mpratt/Embera/pull/57
