### ISSUE TITLE
youtube rel=0  ?

### ISSUE THREAD

**Issue by interfixnet** [mpratt/Embera#62]
Am I correct in thinking that there is no support in Embera for the rel=0 youtube parameter that limits related videos to the channel that produced it?

**Comment by mpratt** [comment]
Hi!

You are right! the oembed implementation on Youtube does not support this.
However in version +2.0 of embera you might get away by using filters.

```
$embera = new Embera();
$embera->addFilter(function ($response) {
    if (!empty($response['html']) && $response['embera_provider_name'] == 'Youtube') {
        $response['html'] = str_ireplace('feature=oembed', 'feature=oembed&rel=0', $response['html']);
    }

    return $response;
});
// do your thing
```

However, this is a new version of Embera, so make sure to read the documentation and migrate your code in order to avoid problems.
