### ISSUE TITLE
Twitter embeds don't work on production

### ISSUE THREAD

**Issue by johncarter-** [mpratt/Embera#99]
Thanks for such a great package.

I am using Laravel, locally using Laravel Sail and in production using a Laravel Forge provisioned Digital Ocean droplet.

I am running this code:

```php
Illuminate\Support\Facades\Artisan::command('embed', function () {
    $embera = new \Embera\Embera();

    // $testUrl = 'https://www.youtube.com/watch?v=J---aiyznGQ'; // 👌
    // $testUrl = 'https://vimeo.com/374131624'; // 👌
    // $testUrl = 'https://twitter.com/KYVENetwork/status/1655919857685221376?s=20'; // 💩
    $testUrl = 'https://twitter.com/Interior/status/507185938620219395'; // 💩

    $embedUrlData = $embera->getUrlData($testUrl);

    dump($embedUrlData);
});
```

It seems that Twitter embeds return an empty array every time on production, but work locally. 

Does you have any suggestions why that could be?

Thanks again.

**Comment by johncarter-** [comment]
Oh, mercy!

https://github.com/oscarotero/Embed/issues/518#issuecomment-1585568740

**Comment by mpratt** [comment]
There seems to be a solution to this problem:

Given the ip address ranges described here: https://developer.twitter.com/en/blog/product-news/2022/updated-source-ip-address-range

You need to allow all TCP connections from those IP ranges.

https://300m.com/security/twitter-oembed-broken-on-digitalocean/

Let me know if this works for you.

**Comment by johncarter-** [comment]
I don't really know enough about configuring firewalls to make sense of it unfortunately. Hopefully someone might be able to explain what needs to be done precisely. If I figure it out I will post back here.

I assume that the firewall rule needs setting up on the Digital Ocean side, not Laravel Forge. But when I added the following, my site became unresponsive and didn't allow me to visit it:

![image](https://github.com/mpratt/Embera/assets/3776888/5d21c565-1a9b-4291-be1b-a4cc3dcaf361)

**Comment by johncarter-** [comment]
I can confirm the following works:

1. Go to Digital Ocean control panel > Networking > Firewalls (tab) > Create Firewall

2. Add the following rules:
![image](https://github.com/mpratt/Embera/assets/3776888/127d3e91-8ecd-4933-a51a-92c7c045c023)

3. Assign that rule to your Droplet.

4. Profit 💷

Thanks again for the package and prompt response, it's highly appreciated.

**Comment by mpratt** [comment]
No problem @johncarter- !
Thanks for the feedback, Im closing this issue. :+1:
